services:
  postgres:
    container_name: postgres17_uwa
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uwa_back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  redis:
    container_name: redis_6_uwa
    image: redis:6.2-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./redis_cache:/data

  my-service:
    container_name: uwa_back
    image: uwaback:dev
    restart: always
    env_file:
      - docker.env
    ports:
      - "8081:8081"
    volumes:
      - ./testkey.pem:/root/testkey.pem
      - ./testkey.pub:/root/testkey.pub
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
