export Port=":xxxx"
export AppName="Some app name"
export AppEnv="development"
export AppToken="sometokenhere"
export SqliteDBName="dbnamehere"
export UserTokenLength="999"
export LogFilePath="somepath"